Create over lay menu
pine-book/team7 pull request #7
Opened 2021-07-16 16:48 UTC by pine-book

## 何をしたか？
- イベント追加メニューのポップアップ実装
## やらなかった
- デザインの洗練
## 実装の内容
- JavaScriptの追加
- イベント追加メニューボタンの実装
## 確認事項
- 動作の確認

2021-07-16 17:57 UTC, pine-book commented
## やったこと
- アニメーションの追加など

2021-07-17 10:13 UTC, tiking76 commented
@pine-book 
動作確認のところはページのスクショとか貼っておいて〜

2021-07-17 10:17 UTC, tiking76 requested changes

2021-07-17 10:17 UTC, tiking76 commented on vertida.html
> +         <div class="v78_361"></div>
class名をわかりやすいものに変えてね〜

2021-07-17 10:17 UTC, tiking76 commented on vertida.html
> +                  <span class="v78_371">から</span>
ここも

2021-07-17 10:17 UTC, tiking76 commented on vertida.html
> +                  <span class="v78_376">まで</span>
ここも

2021-07-17 10:42 UTC, pine-book commented
## やったこと
- から　まで　class名を変更
- から　まで　を微調整

2021-07-17 10:57 UTC, tiking76 reviewed
ちょっと多いけどがんばって！！

2021-07-17 10:57 UTC, tiking76 commented on vertida.html
> +                  <input type="text" name="name" placeholder="7/24/12:30" id="form3">
```
<input type="text" name="name" placeholder="イベントを追加" id="form1">
```
name="name"のところをちゃんとした名前に変えてください:pray:

2021-07-17 10:57 UTC, tiking76 commented on vertida.html
> +                  <input type="text" name="name" placeholder="7/24/15:00" id="form2">
ここも

2021-07-17 10:57 UTC, tiking76 commented on vertida.html
> +               <select type="text" name="name" id="form5">
ここも

2021-07-17 11:00 UTC, pine-book commented on vertida.html
> +                  <input type="text" name="name" placeholder="7/24/12:30" id="form3">
name 変更しました

2021-07-17 11:04 UTC, pine-book commented on vertida.html
> +                  <input type="text" name="name" placeholder="7/24/15:00" id="form2">
name 変更しました

2021-07-17 11:57 UTC, pine-book commented
## 出来てないところ
- action 属性にサーバーのURL追加してません。

2021-07-17 12:18 UTC, tiking76 approved these changes
LGTM!

2021-07-17 12:18 UTC, merged